* My Beamer template

Beamer theme obtained as a customization of the [[https://github.com/matze/mtheme][metropolis theme]].


** Tips

*** Figures

    I explicitly set a relative =graphicspath= in the =template.tex= main
    tex file for where I save the images (=./fig_slides/= by default). I
    heavily use =textblock= for positioning of figures, blocks, etc. See
    example usages compiling =template.tex=.

*** Notes on secondary screen

    You can add notes for yourself using =\note= and setting
    =\setbeameroptions{show notes on second screen=right}=. This will
    require a pdf reader that can split each page of the pdf. I use
    [[https://github.com/pdfpc/pdfpc][pdfpc]] for this, which also allows embedding videos.

*** Multimedia

    I am able to play mp4 and gif animations in my slides using the
    multimedia package:

    #+begin_src tex
    \movie[width=0.9\textwidth,height=0.95\textheight,showcontrols=true,autostart=true]{}{./path/to/movie.mp4}
     #+end_src.

    This works at least with  okular and pdfpc as pdf readers.

    Note that =\movie= will not use the =graphicspath= set in the document
    pre-amble.

** Example talks

   Most of my slides available [[https://users.flatironinstitute.org/~mrenzo/talks.html][here]] where made with (an earlier
   version of) this setup.
